#!/bin/bash

set -e

rm packer_virtualbox-iso_virtualbox.box || true
if [ "$OS_PASSWORD" != "" ]; then
  LOG=/tmp/pack_log.$$
  PACKER_RAW=./packer$$.raw
  PACKER_QCOW=./packer$$.qcow2
  rm -f ${LOG} ${PACKER_RAW} ${PACKER_QCOW}
  # Only build on openstack
  packer build -only openstack template.json | tee $LOG
  IMAGEID=`tail -1  $LOG | sed -e 's/.*An image was created: //'`
  if [ -z "${IMAGEID}" ]; then
    echo "IMAGE not getnerated"
    exit 1 ;
  fi
  echo Downloading raw image
  if ! glance image-download --progress --file ${PACKER_RAW} ${IMAGEID} ; then
    echo Error downloading image
    exit 2
  fi
  echo Converting to QCOW2
  if ! qemu-img convert -f raw -O qcow2 ${PACKER_RAW} ${PACKER_QCOW} ; then
    echo Error converting image
    exit 3
  fi
  if ! glance image-create --file ${PACKER_QCOW} --disk-format qcow2 --container-format bare  --progress  --name "Lustre-builder" ; then
    echo Error uploading image
    exit 4
  fi
  echo cleaning local file system
  rm ${PACKER_RAW} ${PACKER_QCOW}
  echo cleaning glance
  glance image-delete ${IMAGEID}
  exit 0;
fi
if [ "$AWS_ACCESS_KEY" != "" ]; then
  packer build -only amazon-ebs template.json
else
  packer build -only virtualbox-iso template.json
  vagrant box remove lustre_precise_build_server || true
  vagrant box add lustre_precise_build_server  packer_virtualbox-iso_virtualbox.box
fi
